// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Rolla.Data;

#nullable disable

namespace Rolla.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250804164949_RSearch")]
    partial class RSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rolla.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoutingDCode")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfCar")
                        .HasColumnType("int");

                    b.HasKey("DriverId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Rolla.Models.MapRouteDriver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Point>("Destination")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("NotFound")
                        .HasColumnType("bit");

                    b.Property<Point>("Origin")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<int>("RoutingDCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MapRouteDrivers");
                });

            modelBuilder.Entity("Rolla.Models.MapRouteRider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Point>("Destination")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("NotFound")
                        .HasColumnType("bit");

                    b.Property<Point>("Origin")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<int>("RoutingDCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MapRouteRiders");
                });

            modelBuilder.Entity("Rolla.Models.Rider", b =>
                {
                    b.Property<int>("RiderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RiderId"));

                    b.Property<int>("RiderType")
                        .HasColumnType("int");

                    b.Property<int>("RoutingRCode")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RiderId");

                    b.ToTable("Riders");
                });
#pragma warning restore 612, 618
        }
    }
}
